---
- hosts: all
  vars:
    localhost: 127.0.0.1
    esxi_datacenter: ha-datacenter
    vm_scsi: paravirtual
    vm_network_adapter_type: vmxnet3
    vm_network_type: standard

  tasks:

  - name: Block to check if the VM name exists in inventory 
    block:
    - name: Check VMFS filesystem for foldername {{ vm_name }}
      stat:
        path: /vmfs/volumes/{{ esxi_datastore }}/{{ vm_name }}/
      register: vmfs_vm_name 

    - name: Check if machine {{ vm_name }} already exists
      delegate_to: "{{ localhost }}"
      vsphere_guest:
        vcenter_hostname: "{{ esxi_hostname }}"
        esxi:
          datacenter: "{{ esxi_datacenter }}"
          hostname: "{{ esxi_hostname }}"
        validate_certs: "{{ esxi_validate_certs |default (false) }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        guest: "{{ vm_name }}"
        vmware_guest_facts: yes
      register: inventory_vm_name
      ignore_errors: yes

# Throw Warnings if datastore foldername exists or machine is arleady in inventory
  - name: Machine folder for {{ vm_name }} exists on datastore
    fail:
      msg:  "There is already a foldername on the datastore {{ esxi_datastore }} with same name as {{ vm_name }} Please backup/rename and run again" 
    when: vmfs_vm_name.stat.exists == true
  - name: Machine {{vm_name }} already exists in inventory
    debug:
      msg: "This VM machine appears to already exist in esxi inventory but not on the datastore; we will forcibly overwrite {{ vm_name }}"  
    when: inventory_vm_name.ansible_facts is defined


# Delete the machine name from if it exists in inventory but not datastore
  - name: Delete machine {{ vm_name }} from inventory 
    delegate_to: "{{ localhost }}"
    vsphere_guest:
      vcenter_hostname: "{{ esxi_hostname }}"
      esxi:
        datacenter: "{{ esxi_datacenter }}"
        hostname: "{{ esxi_hostname }}"
      validate_certs: "{{ esxi_validate_certs |default (false) }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      guest: "{{ vm_name }}"
      state: absent
      force: yes
    when: inventory_vm_name.ansible_facts is defined
  
  
  - name: Block to create new Virtual Machine
    block:
            
    - name: Create machine {{ vm_name }}
      delegate_to: "{{ localhost }}"
      vsphere_guest:
        vcenter_hostname: "{{ esxi_hostname }}"
        esxi:
          datacenter: "{{ esxi_datacenter }}"
          hostname: "{{ esxi_hostname }}"
        validate_certs: "{{ esxi_validate_certs |default (false) }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        guest: "{{ vm_name }}"
        state: present
        vm_extra_config:
          vcpu.hotadd: no 
          mem.hotadd:  no
          notes: ansible made me with <3
        vm_disk:
          disk1:
            size_gb: "{{ vm_disk_size }}"
            type: thin
            datastore: "{{ esxi_datastore }}"
        vm_nic:
          nic1:
            network: "{{ vm_network }}"
            type: "{{ vm_network_adapter_type }}"
            network_type: "{{ vm_network_type }}"
        vm_hardware:
          memory_mb: "{{ vm_ram_size | default (1024) }}"
          num_cpus: "{{ vm_cores | default (1) }}"
          scsi: "{{ vm_scsi }}"
          osid: "{{ vm_guest_id }}"  
      register: create_vm_status
    
    rescue:
    - name: rm dir for new host on vmfs
      shell: "rm -rf /vmfs/volumes/{{ esxi_datastore }}/{{ vm_name }}"
      register: rescue_remove_vm
    - fail:
        msg: Something went wrong on intial VM creation and we have deleted the newly created datastore file
      when: rescue_remove_vm|changed     

  - name: Block for vmkfstools image creation
    block:
    - name: delete empty disk for new template
      shell: "rm -r /vmfs/volumes/{{ esxi_datastore }}/{{ vm_name }}/{{ vm_name }}*.vmdk"
     
    - name: create disk from template
      shell: "vmkfstools -i /vmfs/volumes/{{ esxi_datastore }}/{{ vm_template_path }} /vmfs/volumes/{{ esxi_datastore }}/{{ vm_name }}/{{ vm_name }}.vmdk -d thin"
    when: 
      - create_vm_status is defined and create_vm_status|changed
  
      
  - name: Power on {{ vm_name }}
    delegate_to: "{{ localhost }}"
    vsphere_guest:
      vcenter_hostname: "{{ esxi_hostname }}"
      esxi:
        datacenter: "{{ esxi_datacenter }}"
        hostname: "{{ esxi_hostname }}"
      validate_certs: "{{ esxi_validate_certs | default (false) }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      guest: "{{ vm_name }}"
      state: powered_on

  - name: Wait for SSH on new system
    wait_for_connection:
      delay: 60
      timeout: 300

  - name: Get IP of new machine for SSH {{ vm_name }}
    delegate_to: "{{ localhost }}"
    vsphere_guest:
      vcenter_hostname: "{{ esxi_hostname }}"
      esxi:
        datacenter: "{{ esxi_datacenter }}"
        hostname: "{{ esxi_hostname }}"
      validate_certs: "{{ esxi_validate_certs |default (false) }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      guest: "{{ vm_name }}"
      vmware_guest_facts: yes
    register: get_ip_new_vm

  - name: Get new hostname IP
    debug:
      msg: "{{ get_ip_new_vm.ansible_facts.hw_eth0.ipaddresses[0] }}"

      #- hosts: "{{ get_ip_new_vm.ansible_facts.hw_eth0.ipaddresses }}" 
      #  - name: SSH to host and set hostname
      #    delegate_to: "{{ localhost }}"  # "{{ get_ip_new_vm.ansible_facts.hw_eth0.ipaddresses }}"
      #    raw: "ssh -o StrictHostKeyChecking=no root@{{ get_ip_new_vm.ansible_facts.hw_eth0.ipaddresses[0] }} && hostnamectl set-hostname wienerface.fqdn"
    # name: "{{ vm_name }}"